# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none


pool: default


steps:
- checkout: self
  persistCredentials: true

- script: |
    echo "Build Type: $(BUILD_TYPE)"
  displayName: 'Confirming Variables'

- task: CmdLine@2
  inputs:
    script:
      sfdx sfpowerkit:auth:login -u=$(sfTargetOrgUserName) -p=$(sfTargetOrgPassword) -s=$(sfTargetOrgSecurityToken) -r https://test.salesforce.com  
  displayName: authentication to org

- task: CmdLine@2
  inputs:
    script:
     #sfdx force:source:deploy -u=$(sf.usernameTarget) -x unpackaged/package.xml
     echo "Build Type in Deploy to Target: $(BUILD_TYPE)"
  displayName: Deploy to Target Org
  condition:  or(eq(variables['BUILD_TYPE'], 'deploy'),eq(variables['BUILD_TYPE'], 'both'))