
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none


pool: Syed_Pool


steps:
- checkout: self
  persistCredentials: true

- script: |
    echo "Build Type: $(BUILD_TYPE)"
  displayName: 'Confirming Variables'

- task: CmdLine@2
  inputs:
    script:
      sfdx sfpowerkit:auth:login -u=$(sfTargetOrgUserName) -p=$(sfTargetOrgPassword) -s=$(sfTargetOrgSecurityToken) -r https://test.salesforce.com  
  displayName: authentication to org
   
- task: CmdLine@2
  inputs: 
    script: "sfdx force:source:convert -r ./force-app -d ./toDeploy"
  displayName: Convert to deploy source
    
- task: CmdLine@2
  inputs: 
    script: "sfdx force:mdapi:deploy -l RunSpecifiedTests -r $('cat ApexTest.txt') -c -d ./toDeploy -u $(sfTargetOrgUserName) -w 10"
  displayName: Run validation on source code